# Generated by Django 5.2.3 on 2025-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
