# Generated by Django 5.2.3 on 2025-07-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickapp', '0002_roomid'),
    ]

    operations = [
        migrations.CreateModel(
            name='roomname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
